name: Rust

on:
  [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - id: init
      run: |
        rustup toolchain install stable --profile minimal
        echo "##[set-output name=sha7;]$(echo ${GITHUB_SHA:0:7})"
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release --target x86_64-unknown-linux-musl
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: server-wrapper-${{ steps.init.outputs.sha7 }}
        path: target/release/server-wrapper

